### ISSUE TITLE
[agora_uikit: 1.0.2][flutter_web: 3.0.5] MissingPluginException issue

### ISSUE THREAD

**Issue by hmbenhaim** [AgoraIO-Community/Flutter-UIKit#95]
Hi guys 
I saw that the web support is marked as done so i thought I'll give this package a try. 
i'm looking for a good video calls platform for very long time.

i used the example

my code is
```
import 'package:agora_uikit/agora_uikit.dart';
import 'package:flutter/material.dart';

class CallsView extends StatefulWidget {
  const CallsView({Key? key}) : super(key: key);

  @override
  State<CallsView> createState() => _CallsViewState();
}

class _CallsViewState extends State<CallsView> {
  final AgoraClient client = AgoraClient(
      agoraConnectionData: AgoraConnectionData(
        appId: "******",
        channelName: "test",
        username: "user",
        tempToken:
            "******",
        rtmEnabled: false,
      ),
      enabledPermission: [
        Permission.camera,
        Permission.microphone,
      ]);

  @override
  void initState() {
    super.initState();
    initAgora();
  }

  void initAgora() async {
    await client.initialize();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Agora UIKit'),
          centerTitle: true,
        ),
        body: SafeArea(
          child: Stack(
            children: [
              AgoraVideoViewer(
                client: client,
                layoutType: Layout.floating,
                enableHostControls: true, // Add this to enable host controls
              ),
              AgoraVideoButtons(
                client: client,
              ),
            ],
          ),
      ),
    );
  }
}

```

The error I get
```
Error: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
    at Object.throw_ [as throw] (http://localhost:40000/dart_sdk.js:5080:11)
    at MethodChannel._invokeMethod (http://localhost:40000/packages/flutter/src/services/restoration.dart.lib.js:1567:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:40000/dart_sdk.js:40641:33
    at _RootZone.runUnary (http://localhost:40000/dart_sdk.js:40511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:40000/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:40000/dart_sdk.js:35999:49)
    at _Future._propagateToListeners (http://localhost:40000/dart_sdk.js:36037:17)
    at [_completeWithValue] (http://localhost:40000/dart_sdk.js:35872:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:40000/dart_sdk.js:35906:35)
    at Object._microtaskLoop (http://localhost:40000/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:40000/dart_sdk.js:40784:13)
    at http://localhost:40000/dart_sdk.js:36261:9
```

Thank you

**Comment by Meherdeep** [comment]
Hey @hmbenhaim, UIKit currently supports Android and iOS as of now. We are working on adding support for Web and desktop. In the meanwhile you can use the [agora_rtc_engine](https://pub.dev/packages/agora_rtc_engine) package to add web support for your application.
